using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.XR.iOS;

public class ARKit_placeme : MonoBehaviour {

	public GameObject collBallPrefab;
	private GameObject collBallGO;

	public float maxRayDistance = 30.0f;
	public LayerMask collisionLayer = 1 << 10;  //ARKitPlane layer

	// Use this for initialization
	void Start () {

	}

	void CreateMoveBall( Vector3 explodePosition)
	{
		collBallGO = Instantiate (collBallPrefab, explodePosition, Quaternion.identity);
	}

	// Update is called once per frame
	void Update () {
		if (Input.GetMouseButtonDown (0)) {
			Ray ray = Camera.main.ScreenPointToRay (Input.mousePosition);
			RaycastHit hit;

			//we'll try to hit one of the plane collider gameobjects that were generated by the plugin
			//effectively similar to calling HitTest with ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent
			if (Physics.Raycast (ray, out hit, maxRayDistance, collisionLayer)) {
				//we're going to get the position from the contact point
					//m_HitTransform.position = hit.point;
				Debug.Log (string.Format ("x:{0:0.######} y:{1:0.######} z:{2:0.######}", hit.point.x, hit.point.y, hit.point.z));

				//and the rotation from the transform of the plane collider
					//m_HitTransform.rotation = hit.transform.rotation;

				CreateMoveBall (hit.point);

				Debug.Log("THIS IS ACTUALLY RUNNING");
			}
		}

	}
}
